import fs from "node:fs/promises";

const root = new URL("../", import.meta.url);
const readmePath = new URL("README.md", root);
const configPath = new URL("config/youtube.json", root);

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function textBetween(block, tag) {
  const match = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, "i"));
  return match ? match[1].replaceAll("<![CDATA[", "").replaceAll("]]>", "").trim() : "";
}

async function getVideos(config) {
  if (!config.channelId) return [];
  const feedUrl = `https://www.youtube.com/feeds/videos.xml?channel_id=${config.channelId}`;
  const response = await fetch(feedUrl, { headers: { "user-agent": "sam-codex-profile-updater" } });
  if (!response.ok) return [];
  const xml = await response.text();
  const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/gi)].map((m) => m[1]).slice(0, config.maxVideos || 5);
  const videos = entries.map((entry) => {
    const videoId = textBetween(entry, "yt:videoId");
    const link = `https://www.youtube.com/watch?v=${videoId}`;
    return {
      videoId,
      title: textBetween(entry, "title") || "Untitled video",
      url: link,
      thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      published: textBetween(entry, "published"),
      views: ""
    };
  });

  const apiKey = process.env.YOUTUBE_API_KEY;
  if (apiKey && config.includeStatsWithApiKey && videos.length > 0) {
    const ids = videos.map((video) => video.videoId).join(",");
    const statsResponse = await fetch(`https://www.googleapis.com/youtube/v3/videos?part=statistics&id=${ids}&key=${apiKey}`);
    if (statsResponse.ok) {
      const stats = await statsResponse.json();
      const byId = new Map((stats.items || []).map((item) => [item.id, item.statistics?.viewCount || ""]));
      for (const video of videos) video.views = byId.get(video.videoId) || "";
    }
  }
  return videos;
}

function render(videos) {
  if (videos.length === 0) {
    return `<table>
  <tr>
    <td width="20%" align="center"><strong>YouTube</strong></td>
    <td width="80%"><strong>Latest five videos sync every six hours.</strong><br /><sub>Thumbnail, title, published date, watch button, and optional view counts are generated by workflow.</sub></td>
  </tr>
</table>`;
  }

  return `<table>
${videos.map((video) => `  <tr>
    <td width="28%"><a href="${escapeHtml(video.url)}"><img src="${escapeHtml(video.thumbnail)}" width="180" alt="${escapeHtml(video.title)} thumbnail" /></a></td>
    <td width="72%"><strong>${escapeHtml(video.title)}</strong><br /><sub>Published: ${escapeHtml(video.published ? new Date(video.published).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }) : "Unknown")}${video.views ? ` | Views: ${Number(video.views).toLocaleString("en-US")}` : ""}</sub><br /><a href="${escapeHtml(video.url)}"><img src="https://img.shields.io/badge/Watch-YouTube-D6AF36?style=for-the-badge&logo=youtube&labelColor=0B0B0D" alt="Watch video" /></a></td>
  </tr>`).join("\n")}
</table>`;
}

function replaceBlock(readme, marker, content) {
  const start = `<!-- ${marker}:START -->`;
  const end = `<!-- ${marker}:END -->`;
  return readme.replace(new RegExp(`${start}[\\s\\S]*?${end}`), `${start}\n${content}\n${end}`);
}

const config = JSON.parse(await fs.readFile(configPath, "utf8"));
const videos = await getVideos(config);
const readme = await fs.readFile(readmePath, "utf8");
await fs.writeFile(readmePath, replaceBlock(readme, "YOUTUBE-FEED", render(videos)));
